import type { Role } from '@/generated/prisma'

export enum RbacPermission {
  CREATE_WAREHOUSE = 'CREATE_WAREHOUSE',
  ARCHIVE_WAREHOUSE = 'ARCHIVE_WAREHOUSE',
  CREATE_ZONE = 'CREATE_ZONE',
  CREATE_BIN = 'CREATE_BIN',
  BLOCK_UNBLOCK_BIN = 'BLOCK_UNBLOCK_BIN',
  ITEM_CREATE = 'ITEM_CREATE',
  ITEM_EDIT = 'ITEM_EDIT',
  ORDER_DRAFT_CREATE = 'ORDER_DRAFT_CREATE',
  ORDER_CONFIRM_RELEASE = 'ORDER_CONFIRM_RELEASE',
  ORDER_CANCEL = 'ORDER_CANCEL',
  ORDER_EXECUTE_FLOOR = 'ORDER_EXECUTE_FLOOR',
  ORDER_SIGN_OFF_EXECUTED = 'ORDER_SIGN_OFF_EXECUTED',
  ASSIGN_WW_TO_ZONE = 'ASSIGN_WW_TO_ZONE',
  ASSIGN_WM_TO_WAREHOUSE = 'ASSIGN_WM_TO_WAREHOUSE',
  USER_MANAGE_OFFICE_STAFF = 'USER_MANAGE_OFFICE_STAFF',
  USER_CHANGE_ROLE = 'USER_CHANGE_ROLE',
  ZONE_PERMISSION_OVERRIDE = 'ZONE_PERMISSION_OVERRIDE',
  REPORT_VIEW = 'REPORT_VIEW',
  REPORT_VIEW_ACTIVITY_AUDIT = 'REPORT_VIEW_ACTIVITY_AUDIT',
  ALERT_RULE_CONFIGURE = 'ALERT_RULE_CONFIGURE',
  DELETE_OFFICE_RECORD = 'DELETE_OFFICE_RECORD',
  DELETE_WAREHOUSE_RECORD = 'DELETE_WAREHOUSE_RECORD'
}

const om: RbacPermission[] = [
  RbacPermission.CREATE_ZONE,
  RbacPermission.CREATE_BIN,
  RbacPermission.BLOCK_UNBLOCK_BIN,
  RbacPermission.ITEM_CREATE,
  RbacPermission.ITEM_EDIT,
  RbacPermission.ORDER_DRAFT_CREATE,
  RbacPermission.ORDER_CONFIRM_RELEASE,
  RbacPermission.ORDER_CANCEL,
  RbacPermission.ASSIGN_WW_TO_ZONE,
  RbacPermission.ASSIGN_WM_TO_WAREHOUSE,
  RbacPermission.USER_MANAGE_OFFICE_STAFF,
  RbacPermission.USER_CHANGE_ROLE,
  RbacPermission.ZONE_PERMISSION_OVERRIDE,
  RbacPermission.REPORT_VIEW,
  RbacPermission.REPORT_VIEW_ACTIVITY_AUDIT,
  RbacPermission.ALERT_RULE_CONFIGURE,
  RbacPermission.DELETE_OFFICE_RECORD
]

const ow: RbacPermission[] = [
  RbacPermission.ORDER_DRAFT_CREATE,
  RbacPermission.REPORT_VIEW
]

const wm: RbacPermission[] = [
  RbacPermission.CREATE_ZONE,
  RbacPermission.CREATE_BIN,
  RbacPermission.BLOCK_UNBLOCK_BIN,
  RbacPermission.ORDER_DRAFT_CREATE,
  RbacPermission.ORDER_CONFIRM_RELEASE,
  RbacPermission.ORDER_CANCEL,
  RbacPermission.ORDER_EXECUTE_FLOOR,
  RbacPermission.ORDER_SIGN_OFF_EXECUTED,
  RbacPermission.ASSIGN_WW_TO_ZONE,
  RbacPermission.REPORT_VIEW,
  RbacPermission.DELETE_WAREHOUSE_RECORD
]

const ww: RbacPermission[] = [
  RbacPermission.ORDER_EXECUTE_FLOOR
]

function toSet(perms: RbacPermission[]): ReadonlySet<RbacPermission> {
  return new Set(perms)
}

export const ROLE_PERMISSIONS: Record<
  Exclude<Role, 'OWNER'>,
  ReadonlySet<RbacPermission>
> = {
  OFFICE_MANAGER: toSet(om),
  OFFICE_WORKER: toSet(ow),
  WAREHOUSE_MANAGER: toSet(wm),
  WAREHOUSE_WORKER: toSet(ww)
}
